/* 
 * Trigger que atualiza o valor da fatura quando removido alguma parcela
 */
/**
 * Author:  Vanderlei Fiorentin
 * Created: 13 de mar. de 2021
 */

CREATE TRIGGER "TGR_REMOVER_PARCELA_FATURA" AFTER DELETE ORDER 1 ON "financeiro"."PARCELAS_LANCTO_CONTABIL" REFERENCING OLD AS OLD_PARCELA FOR EACH ROW /* WHEN( search_condition ) */
BEGIN		

    DECLARE vCartao INTEGER;

    SELECT L.ID_CARTAO
      INTO vCartao 
      FROM LANCTOS_CONTABEIS AS L 
     WHERE L.ID_LANCTO = OLD_PARCELA.ID_LANCTO;

    UPDATE FATURAS SET FATURAS.VALOR = FATURAS.VALOR - OLD_PARCELA.VALOR WHERE FATURAS.ID_FATURA = OLD_PARCELA.ID_FATURA;

    IF(vCartao IS NOT NULL) THEN
        UPDATE CARTOES_CREDITO AS CARTOES SET CARTOES.LIMITE_UTILIZADO = CARTOES.LIMITE_UTILIZADO - OLD_PARCELA.VALOR WHERE CARTOES.ID_CARTAO = vCartao;
    END IF;
END;